# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f9bb4b54ce417a8ba720d50a257507d342743c559e1d296bd9d036d2ab907b93819a0f05abcc1ac29ece1de033a4bd48199027cc6a1e8b632b507383082360c0

test:
  secret_key_base: 3f874f445b8ac0add94a814bd9dfe9818709824d9d003ecdff4281add85b4a2536f07d12d6979b10ebe000dd53f6687c02bb2341bd9419727f48982aa08cce35

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
